ElisExpress/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ElisExpress.Models;
using ElisExpress.Repositories;
using ElisExpress.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ElisExpress.Controllers
{
    public class CarritoController : Controller
    {
        private RepositorioCarritos repositorioCarritos;
        private IConfiguration Configuration;
        private string ApiBaseUrl;

        public CarritoController(RepositorioCarritos repositorioCarritos, IConfiguration configuration)
        {
            this.repositorioCarritos = repositorioCarritos;
            Configuration = configuration;

            ApiBaseUrl = Configuration.GetValue<string>("WebAPIBaseUrl");
        }

        public IActionResult Carritos()
        {

            var modelo = new CarritoViewModel();

            modelo.Carritos = repositorioCarritos.ObtenerCarritos();

            return View(modelo);
        }


        public ActionResult create()
        {
            return View();
        }


    } // FIN
}

ElisExpress/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ElisExpress.Models;
using ElisExpress.Repositories;
using ElisExpress.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ElisExpress.Controllers
{
    public class CategoriaController : Controller
    {
        private RepositorioCategorias repositorioCategorias;
        private IConfiguration Configuration;
        private string ApiBaseUrl;

        public CategoriaController(RepositorioCategorias repositorioCategorias, IConfiguration configuration)
        {
            this.repositorioCategorias = repositorioCategorias;
            Configuration = configuration;

            ApiBaseUrl = Configuration.GetValue<string>("WebAPIBaseUrl");
        }

        public IActionResult Categorias()
        {

            var modelo = new CategoriaViewModel();

            modelo.Categorias = repositorioCategorias.ObtenerCategorias();

            return View(modelo);
        }

        [HttpGet]
        public IActionResult CrearCategoria()
        {

            return View();
        }


        [HttpPost]
        public IActionResult CrearCategoria(Categoria categoria)
        {
            var postExitoso = repositorioCategorias.CrearCategoria(categoria); //Ir a la base de datos a guardarlo 
            if (postExitoso)
            {
                return RedirectToAction("Categorias");
            }
            else
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, "No se pudo realizar el registro");
                return View();
            }
           
        }

        public IActionResult BorrarCategoria(int id)
        {
            var deleteExitoso = repositorioCategorias.BorrarCategoria(id);
            return RedirectToAction("Categorias");
        }
    }
}

ElisExpress/Controllers/FacturaController.cs
using ElisExpress.Repositories;
using ElisExpress.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElisExpress.Controllers
{
    public class FacturaController : Controller
    {
        private RepositorioFacturas repositorioFacturas;
        private IConfiguration Configuration;
        private string ApiBaseUrl;

        public FacturaController(RepositorioFacturas repositorioFacturas, IConfiguration configuration)
        {
            this.repositorioFacturas = repositorioFacturas;
            Configuration = configuration;

            ApiBaseUrl = Configuration.GetValue<string>("WebAPIBaseUrl");
        }

        public IActionResult Facturas()
        {

            var modelo = new FacturaViewModel();

            modelo.Facturas = repositorioFacturas.ObtenerFacturas();

            return View(modelo);
        }


        public ActionResult create()
        {
            return View();
        }
    }
}

ElisExpress/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ElisExpress.Models;
using ElisExpress.Repositories;
using ElisExpress.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ElisExpress.Controllers
{
    public class ProductoController : Controller
    {
        private RepositorioProductos repositorioProductos;
        private IConfiguration Configuration;
        private string ApiBaseUrl;

        public ProductoController(RepositorioProductos repositorioProductos, IConfiguration configuration)
        {
            this.repositorioProductos = repositorioProductos;
            Configuration = configuration;

            ApiBaseUrl = Configuration.GetValue<string>("WebAPIBaseUrl");
        }

        public IActionResult Productos()
        {

            var modelo = new ProductoViewModel();

            modelo.Productos = repositorioProductos.ObtenerProductos();

            return View(modelo);
        }

        [HttpGet]
        public ActionResult CrearProducto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearProducto(Producto producto)
        {
            var postExitoso = repositorioProductos.CrearProducto(producto); //Ir a la base de datos a guardarlo 
            if (postExitoso)
            {
                return RedirectToAction("Productos");
            }
            else
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, "No se pudo realizar el registro");
                return View();
            }
            
        }




    } // FIN
}

ElisExpress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElisExpress</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/notify.min.js"></script>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>


    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/index.css" rel="stylesheet" />
    <link href="~/Content/Stars.css" rel="stylesheet" />

    <script src="~/Scripts/Views/Kart.js"></script>
    <script src="../Scripts/Views/vProductos.js"></script>
    <link href="~/Content/Aurotizacion.css" rel="stylesheet" />
    <script src="~/Content/Chart.min.js"></script>
    <script src="~/Scripts/moment.min.js.js"></script>
    <script src="~/Scripts/vSesion.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="~/Scripts/Layout.js"></script>

    <!-- Scripts cloudinary -->
    <script src='https://cdn.jsdelivr.net/jquery.cloudinary/1.0.18/jquery.cloudinary.js' type='text/javascript'></script>
    <script src="https://widget.cloudinary.com/global/all.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Categorias">Categorías</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Productos">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carrito" asp-action="Carritos">Carrito</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Factura" asp-action="Facturas">Facturas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ElisExpress - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>